version: "3.8"

services:
  cypress:
    image: realestate-scrapper
    build: .
    volumes:
      - "./cypress:/app/cypress"
      - "./data:/app/data"
    command: "npx cypress run --spec cypress/integration/olx.spec.js"
      