version: '2.2'

services:
    cypress:
        image: realestate-scrapper
        build: .
        volumes: 
          - "./cypress:/app/cypress"
          - "./config:/app/config"
          - "./services.yml:/app/services.yml"
          - "./data:/app/data"